# Generated by Django 6.0.2 on 2026-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frontpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainheading', models.CharField(max_length=200)),
                ('firstimage', models.ImageField(upload_to='portfolios/')),
                ('slogon', models.CharField(max_length=200)),
            ],
        ),
    ]
