# Generated by Django 6.0.2 on 2026-06-06 05:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frontpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainheading', models.CharField(max_length=200)),
                ('firstimage', models.ImageField(upload_to='portfolios/')),
                ('slogon', models.CharField(max_length=200)),
                ('about', ckeditor.fields.RichTextField()),
                ('contactmeheading', models.CharField(max_length=200)),
                ('contactme', ckeditor.fields.RichTextField()),
                ('social1', models.URLField(blank=True)),
                ('social2', models.URLField(blank=True)),
                ('social3', models.URLField(blank=True)),
                ('social4', models.URLField(blank=True)),
                ('social5', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
